import type { Metadata } from "next";
import { Inter, Press_Start_2P } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import { Heading, Text, Theme } from "@radix-ui/themes";
import classNames from "classnames";

import "@radix-ui/themes/styles.css";
import { space } from "postcss/lib/list";
import BottomNavigator from "@/components/BottomNavigator";

const inter = Inter({ subsets: ["latin"] });
const press = Press_Start_2P({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-space",
});

export const metadata: Metadata = {
  title: "BlockWhisper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames(press.variable, "flex justify-center")}>
        <Theme
          accentColor={"purple"}
          panelBackground={"translucent"}
          appearance={"dark"}
          className={"w-full max-w-xl"}
        >
          <Providers>
            <div className={"text-white overflow-x-hidden min-h-screen"}>
              <header
                className={
                  "flex items-center flex-col justify-center p-5 gap-4"
                }
              >
                <div className={"px-2 py-1 bg-accent rounded-xl"}>
                  <Text size={"4"}>Reputation: 10</Text>
                </div>
                <Heading size={"8"} as={"h3"} className={"font-display mx-6"}>
                  BlockWhisper
                </Heading>
              </header>
              {children}
            </div>
            <BottomNavigator />
          </Providers>
        </Theme>
      </body>
    </html>
  );
}
